// Available color combinations for sidebar/header
export default [
    'bg-primary text-lighter',
    'bg-secondary text-lighter',
    'bg-success text-lighter',
    'bg-info text-lighter',
    'bg-warning text-darker',
    'bg-danger text-lighter',
    'bg-light text-darker',
    'bg-dark text-lighter',
    'bg-focus text-lighter',
    'bg-alternate text-lighter',

    'bg-vicious-stance text-lighter',
    'bg-midnight-bloom text-lighter',
    'bg-night-sky text-lighter',
    'bg-slick-carbon text-lighter',
    'bg-asteroid text-lighter',
    'bg-royal text-lighter',
    'bg-warm-flame text-darker',
    'bg-night-fade text-darker',
    'bg-sunny-morning text-darker',
    'bg-tempting-azure text-darker',
    'bg-amy-crisp text-darker',
    'bg-heavy-rain text-darker',
    'bg-mean-fruit text-darker',
    'bg-malibu-beach text-darker',
    'bg-deep-blue text-darker',
    'bg-ripe-malin text-lighter',
    'bg-arielle-smile text-lighter',
    'bg-plum-plate text-lighter',
    'bg-happy-fisher text-darker',
    'bg-happy-itmeo text-darker',
    'bg-mixed-hopes text-lighter',
    'bg-strong-bliss text-lighter',
    'bg-grow-early text-lighter',
    'bg-love-kiss text-lighter',
    'bg-premium-dark text-lighter',
    'bg-happy-green text-lighter',
];
